package com.mongo.sequence.model;

import java.io.Serializable;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@Document(collection = "Users")
public class User implements Serializable{

  /**
	 * 
	 */
	private static final long serialVersionUID = -314164285634884017L;
	
  @Transient
  public static final String SEQUENCE_NAME = "username_sequence";
	
	
  @Id
  private String id;
  private String name;
  private String userName; //Autogenerated
  private String email;


}